dungeons:
  example:
    # Name of dungeon
    name: 'Example'
    # World of dungeon
    world: 'world'
    # Spawn point for players
    spawn:
      x: 1
      y: 1
      z: 1
      yaw: 0
      pitch: 0
    # Spawn point for boss mob
    bossSpawn:
      x: 1
      y: 1
      z: 1
    # Spawn points for mobs
    mobSpawns:
      loc1:
        x: 1
        y: 1
        z: 1