spawn:
  ==: org.bukkit.Location
  world: world
  x: 19.21503342561479
  y: 144.0
  z: 90.21659636344998
  pitch: 26.46552
  yaw: -93.31634
dungeons:
  one:
    # Name of dungeon
    name: '&d&lDungeon One'
    # slot in gui
    slot: 21
    # material in select screen
    material: "string"
    # World of dungeon
    world: 'world'
    # Spawn point for players
    spawn:
      x: 1
      y: 1
      z: 1
      yaw: 0
      pitch: 0
    # Spawn point for boss mob
    bossSpawn:
      x: 1
      y: 1
      z: 1
    # Spawn points for mobs
    mobSpawns:
      loc1:
        x: 1
        y: 1
        z: 1
  two:
    # Name of dungeon
    name: '&d&lDungeon Two'
    # slot in gui
    slot: 22
    # material in select screen
    material: "bone"
    # World of dungeon
    world: 'world'
    # Spawn point for players
    spawn:
      x: 1
      y: 1
      z: 1
      yaw: 0
      pitch: 0
    # Spawn point for boss mob
    bossSpawn:
      x: 1
      y: 1
      z: 1
    # Spawn points for mobs
    mobSpawns:
      loc1:
        x: 1
        y: 1
        z: 1
  three:
    # Name of dungeon
    name: '&d&lDungeon Three'
    # slot in gui
    slot: 23
    # material in select screen
    material: "spider_eye"
    # World of dungeon
    world: 'world'
    # Spawn point for players
    spawn:
      x: 1
      y: 1
      z: 1
      yaw: 0
      pitch: 0
    # Spawn point for boss mob
    bossSpawn:
      x: 1
      y: 1
      z: 1
    # Spawn points for mobs
    mobSpawns:
      loc1:
        x: 1
        y: 1
        z: 1