spawn:
  ==: org.bukkit.Location
  world: world
  x: 19.21503342561479
  y: 144.0
  z: 90.21659636344998
  pitch: 26.46552
  yaw: -93.31634
dungeons:
  one:
    # Name of dungeon
    name: 'One'
    # World of dungeon
    world: 'world'
    # Spawn point for players
    spawn:
      x: 1
      y: 1
      z: 1
      yaw: 0
      pitch: 0
    # Spawn point for boss mob
    bossSpawn:
      x: 1
      y: 1
      z: 1
    # Spawn points for mobs
    mobSpawns:
      loc1:
        x: 1
        y: 1
        z: 1